// <auto-generated />
using System;
using CycleScoresWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CycleScoresWeb.Migrations
{
    [DbContext(typeof(CycleScoresWebContext))]
    [Migration("20260529172427_AdditionalCommuniques")]
    partial class AdditionalCommuniques
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CycleScoresWeb.Models.CommuniqueSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CommuniqueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommuniqueTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CycleEventId")
                        .HasColumnType("int");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CycleEventId");

                    b.HasIndex("RaceId");

                    b.ToTable("CommuniqueSet");
                });

            modelBuilder.Entity("CycleScoresWeb.Models.CycleEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("CycleScoresWeb.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CycleEventId")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RaceDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ResultCommuniqueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("StartCommuniqueID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CycleEventId");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("CycleScoresWeb.Models.CommuniqueSet", b =>
                {
                    b.HasOne("CycleScoresWeb.Models.CycleEvent", null)
                        .WithMany("EventCommuniques")
                        .HasForeignKey("CycleEventId");

                    b.HasOne("CycleScoresWeb.Models.Race", null)
                        .WithMany("AdditionalCommuniques")
                        .HasForeignKey("RaceId");
                });

            modelBuilder.Entity("CycleScoresWeb.Models.Race", b =>
                {
                    b.HasOne("CycleScoresWeb.Models.CycleEvent", null)
                        .WithMany("EventRaces")
                        .HasForeignKey("CycleEventId");
                });

            modelBuilder.Entity("CycleScoresWeb.Models.CycleEvent", b =>
                {
                    b.Navigation("EventCommuniques");

                    b.Navigation("EventRaces");
                });

            modelBuilder.Entity("CycleScoresWeb.Models.Race", b =>
                {
                    b.Navigation("AdditionalCommuniques");
                });
#pragma warning restore 612, 618
        }
    }
}
